<script lang="ts">
  import Icon from "$lib/Icon.svelte";
  import { generateRandomHex } from "$lib/random";

  let length = $state("32");
  let output = $state("");
  let error = $state("");
  let copied = $state(false);

  function generate() {
    error = "";
    try {
      output = generateRandomHex(Number(length));
    } catch (cause) {
      output = "";
      error = cause instanceof Error ? cause.message : "Enter a valid length.";
    }
  }

  async function copyOutput() {
    if (!output) return;
    await navigator.clipboard.writeText(output);
    copied = true;
    window.setTimeout(() => (copied = false), 1600);
  }
</script>

<section class="hash-tool">
  <div class="panel generator">
    <div class="generator-head">
      <div>
        <strong>Secure random hash</strong>
        <span>Lowercase hexadecimal generated by the Web Crypto API.</span>
      </div>
      <label class="length-field">
        <span>Length</span>
        <input bind:value={length} type="number" min="1" step="1" inputmode="numeric" />
      </label>
    </div>
    {#if error}<p class="error" role="alert">{error}</p>{/if}
    <button class="primary" type="button" onclick={generate}>Generate hash</button>
  </div>

  <div class="panel output-panel">
    <div class="output-head">
      <span>Output</span>
      <button type="button" onclick={copyOutput} disabled={!output}>
        <Icon name={copied ? "check" : "copy"} />
        {copied ? "Copied" : "Copy"}
      </button>
    </div>
    <code class:placeholder={!output}>{output || "Your secure random value appears here."}</code>
  </div>
</section>

<style>
  .hash-tool {
    max-width: 760px;
    display: grid;
    gap: 12px;
  }
  .panel {
    border: 1px solid var(--line);
    border-radius: var(--radius);
    background: var(--paper);
  }
  .generator {
    padding: 20px;
    display: grid;
    gap: 20px;
  }
  .generator-head {
    display: flex;
    align-items: start;
    justify-content: space-between;
    gap: 16px;
  }
  .generator-head > div {
    display: grid;
    gap: 4px;
  }
  .generator-head strong {
    font-size: 15px;
  }
  .generator-head span {
    color: var(--muted);
    font-size: 13px;
  }
  .length-field {
    display: grid;
    gap: 6px;
    flex: 0 0 100px;
  }
  .length-field > span,
  .output-head > span {
    color: var(--muted);
    font-size: 12px;
    font-weight: 600;
  }
  .length-field input {
    width: 100%;
    height: 38px;
    padding: 0 10px;
    border: 1px solid var(--line-strong);
    border-radius: 6px;
    outline: 0;
    background: white;
    font-family: var(--mono);
  }
  .length-field input:focus {
    border-color: var(--green);
    box-shadow: 0 0 0 3px rgb(35 95 69 / 10%);
  }
  .primary {
    height: 40px;
    padding: 0 16px;
    border: 1px solid var(--ink);
    border-radius: 6px;
    background: var(--ink);
    color: white;
    font-weight: 600;
  }
  .primary:hover {
    background: var(--green);
    border-color: var(--green);
  }
  .error {
    margin: 0;
    padding: 10px 12px;
    border: 1px solid #ebc7be;
    border-radius: 6px;
    background: var(--red-soft);
    color: var(--red);
    font-size: 13px;
  }
  .output-panel {
    min-height: 150px;
    padding: 14px 16px;
    display: grid;
    align-content: start;
    gap: 18px;
    background: #f7f6f0;
  }
  .output-head {
    display: flex;
    align-items: center;
    justify-content: space-between;
  }
  .output-head button {
    padding: 4px 0 4px 8px;
    display: flex;
    align-items: center;
    gap: 5px;
    border: 0;
    background: transparent;
    color: var(--green);
    font-size: 12px;
    font-weight: 600;
  }
  .output-head button :global(svg) {
    width: 13px;
    height: 13px;
  }
  .output-panel > code {
    overflow-wrap: anywhere;
    color: var(--green);
    font-family: var(--mono);
    font-size: 14px;
    line-height: 1.6;
  }
  .output-panel > code.placeholder {
    color: var(--faint);
    font-family: inherit;
    font-size: 13px;
  }
  @media (max-width: 520px) {
    .generator-head {
      display: grid;
    }
    .length-field {
      width: 100px;
    }
  }
</style>
